import { describe,it,expect } from 'vitest';
import { NativeEngine, type NativeObservation, type NativeProcess } from '../src/native-engine';
import { classifyOpening, mirrorLake, mirrorLight, quotaExcessBeforeOpen } from '../src/mirror-lake';
import { settleFocus, cancelFocus } from '../src/focus';
import { parseState, pruneHistory } from '../src/state';
import { dayKey } from '../src/time';
const at=Date.parse('2026-10-07T10:00:00+08:00');
const bili:NativeProcess={pid:99,startedAt:at-1000,executable:'/test/bili',bundleId:'com.bilibili.bilibiliPC',protected:false};
function obs(n:number,frontBundleId='com.apple.Safari'):NativeObservation { return {at:at+n*1000,monotonicMs:100000+n*1000,idleSeconds:0,locked:false,frontBundleId,processes:[bili]}; }
function setup() { const e=new NativeEngine();const rule=e.policy().rules.find(r=>r.targetId==='bilibili-app')!;Object.assign(rule,{dailyMinutes:null,dailyOpens:1,breakEveryMinutes:null,mode:'gentle'});e.setEnabled(true);return e; }
describe('mirror lake',()=>{
 it('only records excess starting at N+1; repeated samples and prompt return do not create holes',()=>{const e=setup();e.tick(obs(0));e.tick(obs(1,bili.bundleId));e.tick(obs(2,bili.bundleId));expect(e.policy().opens[0].quotaExceeded).toEqual([]);e.prepareReturn(bili);e.tick(obs(3,bili.bundleId));expect(e.policy().opens).toHaveLength(1);e.tick(obs(4));e.tick(obs(5,bili.bundleId));expect(e.policy().opens[1].quotaExceeded).toEqual(['daily-opens']);expect(mirrorLake(e.policy(),at+6000).pending).toHaveLength(1);expect(mirrorLake(e.policy(),at+6000).holes).toHaveLength(0);});
 it('confirmation can be corrected or undone without duplicate holes and survives restart and stale UI saves',()=>{const e=setup();e.policy().rules.find(r=>r.targetId==='bilibili-app')!.dailyOpens=0;e.tick(obs(0));e.tick(obs(1,bili.bundleId));const id=e.policy().opens[0].id;const stale=structuredClone(e.policy());e.classifyOpening(id,'accidental');e.classifyOpening(id,'accidental');expect(mirrorLake(e.policy(),at+2000).holes).toHaveLength(1);stale.rules.find(r=>r.targetId==='bilibili-app')!.dailyOpens=99;e.updatePolicy(JSON.stringify(stale),at+2000);const restored=new NativeEngine(e.serialize());expect(mirrorLake(restored.policy(),at+2000).holes).toHaveLength(1);expect(restored.policy().opens[0].quotaExceeded).toEqual(['daily-opens']);restored.classifyOpening(id,'intentional');expect(mirrorLake(restored.policy(),at+2000).holes).toHaveLength(0);restored.classifyOpening(id,'pending');expect(mirrorLake(restored.policy(),at+2000).pending).toHaveLength(1);});
 it('captures weekday time quotas including earned bonus, disabled rules and zero quota',()=>{const e=setup(),s=e.policy(),r=s.rules.find(r=>r.targetId==='bilibili-app')!;r.weekdays['3']={dailyMinutes:1,dailyOpens:null};s.usage.push({id:'u',targetId:r.targetId,projectId:'personal',start:at-60000,end:at});expect(quotaExcessBeforeOpen(s,r.targetId,at)).toEqual(['daily-time']);s.rewards.push({id:'r',sessionIds:[],targetId:r.targetId,day:dayKey(at,s.settings.timezone),minutes:1});expect(quotaExcessBeforeOpen(s,r.targetId,at)).toEqual([]);r.enabled=false;r.weekdays['3']={dailyMinutes:0,dailyOpens:0};expect(quotaExcessBeforeOpen(s,r.targetId,at)).toEqual([]);r.enabled=true;expect(quotaExcessBeforeOpen(s,r.targetId,at)).toEqual(['daily-time','daily-opens']);});
 it('outside-window and active focus alone do not create quota excess',()=>{const e=setup(),s=e.policy(),r=s.rules.find(r=>r.targetId==='bilibili-app')!;r.dailyOpens=null;r.allowedWindows=[{days:[3],start:1200,end:0}];s.sessions.push({id:'active',startedAt:at,endsAt:at+60000,durationMinutes:1,listIds:['entertainment'],mode:'strict',projectId:'personal',status:'active'});expect(quotaExcessBeforeOpen(s,r.targetId,at)).toEqual([]);});
 it('settled sessions yield one star each, cancelled and active sessions yield none',()=>{const s=setup().policy();const session={id:'focus',startedAt:at-60000,endsAt:at,durationMinutes:1,listIds:[],mode:'gentle' as const,projectId:'personal',status:'active' as const};s.sessions.push(session,{...session,id:'cancelled'},{...session,id:'active',endsAt:at+60000});const cancelled=cancelFocus(s,'cancelled',at-1000,true);const settled=settleFocus(cancelled,at);expect(mirrorLake(settled,at).stars).toHaveLength(1);expect(mirrorLake(settleFocus(settled,at+1000),at+1000).stars).toHaveLength(1);expect(mirrorLake(parseState(JSON.parse(JSON.stringify(settled))),at).stars).toHaveLength(1);});
 it('old records remain compatible and are never retroactively classified',()=>{const s=setup().policy();s.opens.push({id:'legacy',at,targetId:'bilibili-app',kind:'launch'});const parsed=parseState(s);expect(mirrorLake(parsed,at).entries).toHaveLength(0);expect(()=>classifyOpening(parsed,'legacy','accidental')).toThrow();expect(()=>classifyOpening(parsed,'missing','invalid')).toThrow();});
 it('uses local day boundaries and retention consistently',()=>{const s=setup().policy();s.opens.push({id:'old',at:at-91*86400000,targetId:'bilibili-app',kind:'activation',quotaExceeded:['daily-opens'],intention:'accidental'},{id:'yesterday',at:at-86400000,targetId:'bilibili-app',kind:'activation',quotaExceeded:['daily-opens'],intention:'accidental'});expect(mirrorLake(s,at).holes).toHaveLength(1);expect(mirrorLake(s,at,true).holes).toHaveLength(0);expect(mirrorLake(pruneHistory(s,at),at).holes).toHaveLength(1);expect(quotaExcessBeforeOpen(s,'bilibili-app',at)).toEqual([]);});
 it('clamps brightness and preserves the balance of stars and holes',()=>{expect(mirrorLight(0,0)).toBe(0);expect(mirrorLight(5,0)).toBe(1);expect(mirrorLight(7,5)).toBe(.4);expect(mirrorLight(2,9)).toBe(0);expect(mirrorLight(20,0)).toBe(1);});
});
