import { describe,it,expect } from 'vitest';
import { NativeEngine, type NativeObservation, type NativeProcess } from '../src/native-engine';
import { CHALLENGE_TEXT } from '../src/rules';
const at=Date.parse('2026-10-07T10:00:00+08:00');
const bili:NativeProcess={pid:100,startedAt:at-1000,executable:'/test/bili',protected:false,bundleId:'com.bilibili.bilibiliPC'};
const wechat:NativeProcess={...bili,pid:101,bundleId:'com.tencent.xinWeChat'};
function obs(seconds:number,patch:Partial<NativeObservation>={}):NativeObservation {return {at:at+seconds*1000,monotonicMs:100000+seconds*1000,idleSeconds:0,locked:false,frontBundleId:bili.bundleId,processes:[bili],...patch};}
function limited(mode:'friction'|'strict'|'gentle'='friction') {const e=new NativeEngine();Object.assign(e.policy().rules.find(r=>r.targetId==='bilibili-app')!,{dailyMinutes:0,breakEveryMinutes:null,mode});e.setEnabled(true);return e;}
describe('native runtime',()=>{
 it('starts paused and maps installed app bundle IDs, separately from websites',()=>{const e=new NativeEngine();expect(e.tick(obs(0))).toEqual([]);expect(e.policy().targets.find(t=>t.id==='bilibili-app')?.kind).toBe('app');expect(e.policy().rules.map(r=>r.targetId).sort()).toEqual(['bilibili-app','wechat','xiaohongshu','xiaohongshu-app','zhihu']);});
 it('accounts previous foreground, excludes unknown apps, idle and locks',()=>{const e=new NativeEngine();e.setEnabled(true);e.tick(obs(0));e.tick(obs(1));e.tick(obs(2,{frontBundleId:'com.apple.Safari'}));e.tick(obs(3,{frontBundleId:'com.apple.Safari'}));e.tick(obs(4,{locked:true}));e.tick(obs(5,{locked:true}));expect(e.policy().usage.reduce((n,u)=>n+u.end-u.start,0)).toBe(2000);});
 it('establishes baseline without inventing launches and counts a new process once',()=>{const e=new NativeEngine();e.setEnabled(true);e.tick(obs(0));e.tick(obs(1));expect(e.policy().opens).toHaveLength(0);e.tick(obs(2,{processes:[]}));const next={...bili,pid:102,startedAt:at+2500};e.tick(obs(3,{processes:[next]}));e.tick(obs(4,{processes:[next]}));expect(e.policy().opens).toHaveLength(1);const restored=new NativeEngine(e.serialize());restored.tick(obs(5,{processes:[next]}));expect(restored.policy().opens).toHaveLength(1);});
 it('shows a save-work grace, requests normal quit once, never auto force quits',()=>{const e=limited();expect(e.tick(obs(0)).map(c=>c.kind)).toEqual(['show']);expect(e.tick(obs(59))).toEqual([]);expect(e.tick(obs(60)).map(c=>c.kind)).toEqual(['quit']);expect(e.tick(obs(61))).toEqual([]);expect(e.tick(obs(90))).toEqual([]);expect(e.data.notices[0].quit.stage).toBe('needs-confirmation');expect(e.data.notices[0].quit.forceQuitOptIn).toBe(false);});
 it('checks challenge on the native side with monotonic time and expires a five-minute grant',()=>{const e=limited();e.tick(obs(0));const n=e.data.notices[0];expect(()=>e.allow(n.id,at+30000,100001,CHALLENGE_TEXT,'我要观看课程')).toThrow();expect(()=>e.allow(n.id,at+30000,130000,'wrong','我要观看课程')).toThrow();e.allow(n.id,at+30000,130000,CHALLENGE_TEXT,'我要观看课程');expect(e.tick(obs(31))).toEqual([]);expect(e.tick(obs(331)).map(c=>c.kind)).toEqual(['show']);});
 it('strict mode cannot use the challenge and cannot alter active focus rules',()=>{const e=limited('strict');e.tick(obs(0));expect(()=>e.allow(e.data.notices[0].id,at+30000,130000,CHALLENGE_TEXT,'我要观看课程')).toThrow();e.policy().sessions.push({id:'strict',startedAt:at,endsAt:at+600000,durationMinutes:10,listIds:['entertainment'],mode:'strict',projectId:'personal',status:'active'});const candidate=structuredClone(e.policy());candidate.rules[0].enabled=false;expect(()=>e.updatePolicy(JSON.stringify(candidate),at+1000)).toThrow('严格专注');});
 it('foreground entries permit the Nth visit, restrict N+1, and honor changed rules',()=>{const e=new NativeEngine();e.policy().rules.find(r=>r.targetId==='wechat')!.dailyOpens=1;e.setEnabled(true);e.tick(obs(0,{processes:[]}));e.tick(obs(1,{frontBundleId:wechat.bundleId,processes:[wechat]}));expect(e.data.notices).toHaveLength(0);e.tick(obs(2,{processes:[]}));const next={...wechat,pid:222,startedAt:at+2500};expect(e.tick(obs(3,{frontBundleId:wechat.bundleId,processes:[next]})).map(c=>c.kind)).toEqual(['show']);expect(e.data.notices[0].decision.reason).toBe('daily-opens');e.tick(obs(4,{processes:[next]}));expect(e.data.notices).toHaveLength(1);e.policy().rules.find(r=>r.targetId==='wechat')!.dailyOpens=2;e.tick(obs(5,{processes:[next]}));expect(e.data.notices).toHaveLength(0);});
 it('visit override expires even when the process stays running',()=>{const e=new NativeEngine();e.policy().rules.find(r=>r.targetId==='wechat')!.dailyOpens=0;e.setEnabled(true);e.tick(obs(0,{processes:[]}));e.tick(obs(1,{frontBundleId:wechat.bundleId,processes:[wechat]}));e.allow(e.data.notices[0].id,at+1000,101000,'','');expect(e.tick(obs(2,{frontBundleId:wechat.bundleId,processes:[wechat]}))).toEqual([]);expect(e.tick(obs(302,{frontBundleId:wechat.bundleId,processes:[wechat]})).map(c=>c.kind)).toEqual(['show']);});
 it('UI saves cannot replace native counters or completed rewards',()=>{const e=new NativeEngine();const stale=structuredClone(e.policy());e.setEnabled(true);e.tick(obs(0));e.tick(obs(1));stale.rules[0].name='新的规则名称';e.updatePolicy(JSON.stringify(stale),at+1000);expect(e.policy().usage).toHaveLength(1);expect(e.policy().rules[0].name).toBe('新的规则名称');});
 it('pausing cancels pending quit and process disappearance clears notices',()=>{const e=limited();e.tick(obs(0));e.setEnabled(false);expect(e.tick(obs(90))).toEqual([]);expect(e.data.notices).toHaveLength(0);e.setEnabled(true);e.tick(obs(91));e.tick(obs(92,{processes:[]}));expect(e.data.notices).toHaveLength(0);});
});
