import {describe,it,expect} from 'vitest';
import {nativeInitialState,NativeEngine,type NativeObservation} from '../src/native-engine';
import {dailyQuota} from '../src/quota';
import {evaluateRule} from '../src/rules';
const now=Date.parse('2026-10-07T10:00:00+08:00');
function sample() {const state=nativeInitialState();const rule=state.rules.find(r=>r.targetId==='bilibili-app')!;rule.breakEveryMinutes=null;return {state,rule};}
describe('daily quota liquid and counters',()=>{
 it('always includes opening counts alongside elapsed time, even with no opening limit',()=>{const {state,rule}=sample();state.opens.push({id:'1',at:now,targetId:rule.targetId,kind:'activation'},{id:'2',at:now+1,targetId:rule.targetId,kind:'activation'});state.usage.push({id:'u',start:now-600000,end:now,targetId:rule.targetId,projectId:'personal'});const q=dailyQuota(state,rule,now+1);expect(q.opens).toBe(2);expect(q.usedSeconds).toBe(600);expect(q.remainingSeconds).toBe(1200);expect(q.ratio).toBeCloseTo(2/3);});
 it('uses the same weekday limit and rewards as enforcement',()=>{const {state,rule}=sample();rule.weekdays['3']={dailyMinutes:20,dailyOpens:3};state.rewards.push({id:'r',day:'2026-10-07',targetId:rule.targetId,minutes:10,sessionIds:[]});state.usage.push({id:'u',start:now-900000,end:now,targetId:rule.targetId,projectId:'personal'});const q=dailyQuota(state,rule,now);expect(q.totalSeconds).toBe(1800);expect(q.remainingSeconds).toBe(900);expect(q.ratio).toBe(.5);expect(q.limits.dailyOpens).toBe(3);expect(evaluateRule(rule,{now,timezone:state.settings.timezone,usedSeconds:900,opens:0,intent:'continue',continuousSeconds:0,bonusMinutes:10})).toEqual({action:'allow',remainingSeconds:900});});
 it('uses remaining count only for count-only rules, and prioritizes time when both are set',()=>{const {state,rule}=sample();rule.dailyMinutes=null;rule.dailyOpens=10;state.opens.push({id:'1',at:now,targetId:rule.targetId,kind:'activation'});let q=dailyQuota(state,rule,now);expect(q.basis).toBe('opens');expect(q.ratio).toBe(.9);rule.dailyMinutes=30;q=dailyQuota(state,rule,now);expect(q.basis).toBe('time');expect(q.ratio).toBe(1);expect(q.remainingOpens).toBe(9);});
 it('distinguishes unlimited from zero, and clamps exhausted/overdrawn levels',()=>{const {state,rule}=sample();rule.dailyMinutes=null;rule.dailyOpens=null;expect(dailyQuota(state,rule,now).ratio).toBe(null);rule.dailyMinutes=0;expect(dailyQuota(state,rule,now).ratio).toBe(0);rule.dailyMinutes=1;state.usage.push({id:'u',start:now-120000,end:now,targetId:rule.targetId,projectId:'personal'});expect(dailyQuota(state,rule,now).ratio).toBe(0);expect(dailyQuota(state,rule,now).remainingSeconds).toBe(0);});
 it('resets counts at the configured day boundary and splits usage across midnight',()=>{const {state,rule}=sample();const midnight=Date.parse('2026-10-07T00:00:00+08:00');state.opens.push({id:'old',at:midnight-1,targetId:rule.targetId,kind:'activation'},{id:'new',at:midnight+1,targetId:rule.targetId,kind:'activation'});state.usage.push({id:'u',start:midnight-60000,end:midnight+60000,targetId:rule.targetId,projectId:'personal'});const q=dailyQuota(state,rule,now);expect(q.opens).toBe(1);expect(q.usedSeconds).toBe(60);});
 it('reflects real engine visits and excludes automatic prompt returns from the card count',()=>{const e=new NativeEngine();e.setEnabled(true);const p={pid:42,startedAt:now-1000,bundleId:'com.bilibili.bilibiliPC',executable:'/test/bili',protected:false};const tick=(second:number,front:string|null)=>e.tick({at:now+second*1000,monotonicMs:second*1000,idleSeconds:0,locked:false,frontBundleId:front,processes:[p]} satisfies NativeObservation);tick(0,null);tick(1,p.bundleId);tick(2,'local.liubai.native');e.prepareReturn(p);tick(3,p.bundleId);tick(4,null);tick(5,p.bundleId);const rule=e.policy().rules.find(r=>r.targetId==='bilibili-app')!;const q=dailyQuota(e.policy(),rule,now+5000);expect(q.opens).toBe(2);expect(q.usedSeconds).toBe(2);});
});
