import {describe,it,expect} from 'vitest';
import {NativeEngine} from '../src/native-engine';
import {WebQuotaTracker,type WebObservation} from '../src/web-quota';
import {CHALLENGE_TEXT} from '../src/rules';
const at=Date.parse('2026-10-07T10:00:00+08:00');
const observation=(seconds:number,patch:Partial<WebObservation>={}):WebObservation=>({host:'www.zhihu.com',visit:'edge:1:1',active:true,at:at+seconds*1000,monotonicMs:seconds*1000,idleSeconds:0,locked:false,...patch});
function setup(){const s=new NativeEngine().policy();const rule=s.rules.find(r=>r.targetId==='zhihu')!;return {s,rule,tracker:new WebQuotaTracker()};}
describe('desktop website quota',()=>{
 it('adds explicit Zhihu and Xiaohongshu website limits independently from apps',()=>{const {s,tracker}=setup();expect(tracker.observe(s,true,observation(0)).decision.action).toBe('challenge');expect(s.rules.find(r=>r.targetId==='xiaohongshu')?.dailyMinutes).toBe(0);expect(s.rules.find(r=>r.targetId==='xiaohongshu-app')?.dailyMinutes).toBe(20);});
 it('checks domain boundaries and never stores full URLs',()=>{const {s,tracker}=setup();expect(tracker.observe(s,true,observation(0,{host:'zhihu.com.evil.test'})).targetId).toBeUndefined();expect(s.opens).toHaveLength(0);tracker.observe(s,true,observation(1));expect(s.opens[0].targetId).toBe('zhihu');expect(JSON.stringify(s.opens)).not.toContain('https://');});
 it('counts a foreground visit once, counts switching back, and respects N versus N+1',()=>{const {s,rule,tracker}=setup();Object.assign(rule,{dailyMinutes:null,dailyOpens:1});expect(tracker.observe(s,true,observation(0)).decision.action).toBe('allow');tracker.observe(s,true,observation(1));expect(s.opens).toHaveLength(1);tracker.observe(s,true,observation(2,{host:''}));expect(tracker.observe(s,true,observation(3)).decision.reason).toBe('daily-opens');expect(s.opens).toHaveLength(2);});
 it('counts only foreground allowed time, excludes blocked pages, idle, lock and suspend',()=>{const {s,rule,tracker}=setup();tracker.observe(s,true,observation(0));tracker.observe(s,true,observation(1));expect(s.usage).toHaveLength(0);rule.dailyMinutes=30;tracker.observe(s,true,observation(2));tracker.observe(s,true,observation(3));tracker.observe(s,true,observation(4,{locked:true}));tracker.observe(s,true,observation(5,{idleSeconds:90}));tracker.observe(s,true,observation(6,{idleSeconds:91}));tracker.observe(s,true,observation(100));expect(s.usage.reduce((n,u)=>n+u.end-u.start,0)).toBe(1000);});
 it('validates challenge natively and expires the grant after five minutes',()=>{const {s,tracker}=setup();tracker.observe(s,true,observation(0));expect(()=>tracker.allow(s,'zhihu',at+29000,29000,CHALLENGE_TEXT,'查阅一个具体问题')).toThrow();expect(()=>tracker.allow(s,'zhihu',at+30000,30000,'wrong','查阅一个具体问题')).toThrow();tracker.allow(s,'zhihu',at+30000,30000,CHALLENGE_TEXT,'查阅一个具体问题');expect(tracker.observe(s,true,observation(31)).decision.action).toBe('allow');expect(tracker.observe(s,true,observation(331)).decision.action).toBe('challenge');expect(s.openReasons[0].grantedMinutes).toBe(5);});
 it('strict rules cannot be overridden and paused management does not count',()=>{const {s,rule,tracker}=setup();rule.mode='strict';tracker.observe(s,true,observation(0));expect(()=>tracker.allow(s,'zhihu',at+30000,30000,CHALLENGE_TEXT,'查阅一个具体问题')).toThrow();const count=s.opens.length;expect(tracker.observe(s,false,observation(31)).decision.action).toBe('allow');expect(s.opens).toHaveLength(count);});
 it('native saves preserve website usage and reconnect preserves historical counts',()=>{const e=new NativeEngine();const stale=structuredClone(e.policy());e.setEnabled(true);e.observeWebsite(observation(0));e.updatePolicy(JSON.stringify(stale),at+1000);expect(e.policy().opens).toHaveLength(1);expect(new NativeEngine(e.serialize()).policy().opens).toHaveLength(1);});
 it('leaving the browser resets the visit without clearing an existing grant',()=>{const {s,tracker}=setup();tracker.observe(s,true,observation(0));tracker.allow(s,'zhihu',at+30000,30000,CHALLENGE_TEXT,'查阅一个具体问题');tracker.leave();expect(tracker.observe(s,true,observation(31)).decision.action).toBe('allow');expect(s.opens).toHaveLength(2);});
});
