import { Plus, Trash2 } from 'lucide-react';
import type { TimeWindow } from '../../../packages/core/src/model';
const days=['日','一','二','三','四','五','六'];
const time=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const minutes=(s:string)=>{const [h,m]=s.split(':').map(Number);return h*60+m;};
export function AllowedWindowsEditor({windows,onChange}:{windows:TimeWindow[];onChange:(next:TimeWindow[])=>void}) {
  const add=()=>onChange([...windows,{days:[0,1,2,3,4,5,6],start:1200,end:1320}]);
  const patch=(index:number,part:Partial<TimeWindow>)=>onChange(windows.map((w,i)=>i===index?{...w,...part}:w));
  return <section className="form-section allowed-windows"><div className="line-heading"><h3>允许使用时段</h3><button type="button" className="text-button" onClick={add}><Plus size={15}/>添加时段</button></div><p className="small muted">{windows.length?'仅在以下任一时段内允许使用，其他时间触发限制':'尚未限制时段，全天可用添加后可按星期安排多个时段'}</p>{windows.map((w,index)=><fieldset className="allowed-window" key={index}><legend>时段 {index+1}</legend><div className="day-picker" aria-label={`时段 ${index+1} 的星期`}>{days.map((day,i)=><button key={day} type="button" aria-label={`时段 ${index+1} 周${day}`} aria-pressed={w.days.includes(i)} className={w.days.includes(i)?'picked':''} onClick={()=>patch(index,{days:w.days.includes(i)?w.days.filter(d=>d!==i):[...w.days,i]})}>周{day}</button>)}</div><div className="form-grid"><label>开始时间<input type="time" aria-label={`时段 ${index+1} 开始时间`} required value={time(w.start)} onInput={e=>patch(index,{start:minutes(e.currentTarget.value)})}/></label><label>结束时间<input type="time" aria-label={`时段 ${index+1} 结束时间`} required value={time(w.end)} onInput={e=>patch(index,{end:minutes(e.currentTarget.value)})}/></label></div><div className="window-foot"><span>{!w.days.length?'请至少选择一天':w.start===w.end?'开始与结束时间不能相同':w.end<w.start?'结束时间为次日，按开始当天的星期计算':'按本地设置的时区执行'}</span><button type="button" className="text-button danger" aria-label={`删除时段 ${index+1}`} onClick={()=>onChange(windows.filter((_,i)=>i!==index))}><Trash2 size={14}/>删除时段</button></div></fieldset>)}<p className="window-review-help">电脑 App 在时段外打开时，需要留下理由并确认意图选择「无意识打开」会记入镜湖；有明确目的或尚未确认时不计黑洞临时继续使用仍遵守自律等级</p></section>;
}
