import { useState } from 'react';
import { Globe2, FolderOpen, Link2 } from 'lucide-react';
import {callMac,nativeMac,type NativeStatus} from './native';
export function BrowserManagement({status}:{status:NativeStatus|null}) {
  const [browser,setBrowser]=useState('edge');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const connected=!!status?.browserConnected;
  const browsers=status?.connectedBrowsers?.map(b=>b==='edge'?'Microsoft Edge':'Google Chrome').join('、');
  return <section className="white-card spaced browser-management"><div className="section-heading"><div><h2><Globe2 size={19}/> 浏览器管理</h2><p>{connected?(status?.enabled?'已连接扩展，当前网页会按网站规则检查配额':'扩展已连接，管理已暂停'):'尚未连接浏览器扩展，桌面 App 管理不会自动覆盖网页'}</p></div><span className="mode-tag">{connected?'扩展已连接':'等待连接'}</span></div><p className="small muted">知乎、小红书网页版已提供独立规则，默认每日 0 分钟：打开前先等待 30 秒、填写理由并完成挑战，可临时使用 5 分钟你可以在「自律规则」设置正常的每日额度App 与网页版分别统计</p><p className="small muted">{connected?`${browsers??'浏览器'} 已连接 · 每 30 秒自动检查连接，关闭浏览器或停用扩展后最多 90 秒更新状态`:'推荐流隐藏可以独立运行，不代表已连接桌面配额管理；请在下方准备本地连接，并在浏览器扩展页重新加载留白扩展'}</p><details><summary>连接浏览器 / 查看安装步骤</summary><ol><li>选择浏览器，准备本地连接<div className="settings-actions"><select aria-label="需要连接的浏览器" value={browser} onChange={e=>setBrowser(e.target.value)}><option value="edge">Microsoft Edge</option><option value="chrome">Google Chrome</option></select><button className="button secondary" disabled={!nativeMac||busy} onClick={async()=>{setBusy(true);try{setMessage(await callMac<string>('install_browser_host',{browser}));}catch(e){setMessage(String(e));}finally{setBusy(false);}}}><Link2 size={15}/>准备本地连接</button></div></li><li>在浏览器打开 <code>{browser==='edge'?'edge://extensions':'chrome://extensions'}</code>，开启开发人员模式，点击“加载解压缩的扩展”</li><li>选择留白项目的 <code>dist/extension</code> 文件夹<button className="text-button" disabled={!nativeMac} onClick={()=>void callMac('open_extension_folder').catch(e=>setMessage(String(e)))}><FolderOpen size={15}/>打开扩展文件夹</button></li><li>重新加载留白扩展，并刷新已打开的网页；扩展弹窗和本页都显示“已连接”才表示桌面配额已接入其他浏览器需要分别安装；Safari 和不支持扩展的内置浏览器尚未接入</li></ol><p className="small muted">扩展只向本机留白报告受管理网站的平台域名和前台状态，不读取或传送页面正文、搜索词、账号或聊天记录扩展停用后无法拦截网页；连接断开时知乎、小红书会显示连接提醒</p></details>{message&&<p role="status" className="small">{message}</p>}</section>;
}
