import {createPortal} from 'react-dom';
import {useEffect,useRef,useState,type CSSProperties,type DragEvent} from 'react';
import {GripVertical,Plus,Pencil,Trash2,X,CalendarDays} from 'lucide-react';
import type {AppState,FocusSpace,Schedule} from '../../../packages/core/src/model';
import {dropMinute,focusPlacement,formatMinute,placementConflict,putFocusPlacement,spaceTones} from '../../../packages/core/src/focus-spaces';
import {clock} from '../../../packages/core/src/time';
import type {SpaceChange} from './FocusSpaces';
const dayNames=['周日','周一','周二','周三','周四','周五','周六'],dayOrder=[1,2,3,4,5,6,0];
const px=.8,height=1440*px;
type DragItem={kind:'space'|'schedule';id:string};
const timeMinutes=(value:string)=>{const [h,m]=value.split(':').map(Number);return h*60+m;};
const range=(s:Schedule)=>{const w=s.windows[0];return `${dayNames[w.days[0]]} ${formatMinute(w.start)}—${w.end<w.start?'次日 ':''}${formatMinute(w.end)}`;};
function segments(schedule:Schedule){const w=schedule.windows[0],duration=schedule.focusSpace!.durationMinutes,day=w.days[0];return [{day,start:w.start,duration:Math.min(duration,1440-w.start),continued:false},...(w.start+duration>1440?[{day:(day+1)%7,start:0,duration:w.start+duration-1440,continued:true}]:[])];}
export function FocusTimetable({state,change,onSpaces,now}:{state:AppState;change:SpaceChange;onSpaces:()=>void;now:number}){
 const [selected,setSelected]=useState(state.focusSpaces[0]?.id??''),[day,setDay]=useState(1),[start,setStart]=useState('09:00');
 const [drag,setDrag]=useState<DragItem|null>(null),[hover,setHover]=useState<{day:number;start:number}|null>(null);
 const [editing,setEditing]=useState<Schedule|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 const scroll=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(scroll.current)scroll.current.scrollTop=7*60*px;},[]);
 const locked=state.sessions.some(s=>s.status==='active'&&s.mode==='strict'&&now<s.endsAt);
 const selectedSpace=state.focusSpaces.find(s=>s.id===selected);
 const modules=state.schedules.filter(s=>s.focusSpace);
 const resolve=(item:DragItem|null)=>item?.kind==='space'?state.focusSpaces.find(s=>s.id===item.id):modules.find(s=>s.id===item?.id)?.focusSpace;
 const draggedSpace=resolve(drag);
 const beginDrag=(e:DragEvent<HTMLElement>,item:DragItem)=>{if(locked){e.preventDefault();return;}setDrag(item);e.dataTransfer.setData('application/x-liubai-space',JSON.stringify(item));e.dataTransfer.effectAllowed=item.kind==='space'?'copy':'move';e.dataTransfer.setDragImage(e.currentTarget,e.currentTarget.clientWidth/2,0);setError('');};
 const position=(e:DragEvent<HTMLElement>,day:number)=>({day,start:dropMinute(e.clientY-e.currentTarget.getBoundingClientRect().top,height)});
 const place=(space:FocusSpace,day:number,minute:number,id?:string)=>{
  if(locked){setError('严格专注进行中，结束后可调整时间表');return;}
  try{const previous=modules.find(s=>s.id===id);const candidate={...focusPlacement(space,day,minute,id??crypto.randomUUID()),enabled:previous?.enabled??true};const next=putFocusPlacement(state,candidate);change(s=>({...s,schedules:next.schedules}));setError('');setMessage(`已安排「${space.name}」：${range(candidate)} · ${space.durationMinutes} 分钟`);setEditing(null);}catch(e){setError((e as Error).message);}
 };
 const drop=(e:DragEvent<HTMLElement>,day:number)=>{e.preventDefault();const pos=position(e,day);try{const item=JSON.parse(e.dataTransfer.getData('application/x-liubai-space')) as DragItem;const space=resolve(item);if(space)place(space,day,pos.start,item.kind==='schedule'?item.id:undefined);}catch{}setDrag(null);setHover(null);};
 const toggle=(s:Schedule)=>{if(locked)return;try{const next=putFocusPlacement(state,{...s,enabled:!s.enabled});change(st=>({...st,schedules:next.schedules}));setError('');}catch(e){setError((e as Error).message);}};
 const remove=(id:string)=>{if(!locked){change(s=>({...s,schedules:s.schedules.filter(x=>x.id!==id)}));setEditing(null);setMessage('已移除这次安排，专注空间仍然保留');}};
 const ghost=hover&&draggedSpace?focusPlacement(draggedSpace,hover.day,hover.start,drag?.kind==='schedule'?drag.id:'preview'):null;
 const conflict=ghost&&placementConflict(state.schedules,ghost);
 const today=clock(now,state.settings.timezone);
 return <section className="focus-planner"><div className="planner-intro"><CalendarDays size={24}/><div><h2>把专注，放进一周里</h2><p>拖动左侧模块，落点上边缘决定开始时间，模块时长决定结束时间每周重复 · {state.settings.timezone}</p></div></div>
 <p className="planner-policy">留白运行且管理开启时，到点自动开始锁屏、已有专注或错过开始时间时不补开、不补记成果旧版循环限制仍在下方单独管理</p>
 {locked&&<p className="window-review-help">严格专注进行中，时间表暂时不能修改</p>}
 <div className="planner-layout"><aside className="planner-palette"><div className="line-heading"><h3>专注模块</h3><button className="text-button" onClick={onSpaces}>管理空间</button></div>{!state.focusSpaces.length&&<p>先创建一个专注空间，再拖进这一周</p>}{state.focusSpaces.map(space=><button key={space.id} type="button" className="planner-source" style={{'--space-color':spaceTones[space.tone].color} as CSSProperties} draggable={!locked} onDragStart={e=>beginDrag(e,{kind:'space',id:space.id})} onDragEnd={()=>{setDrag(null);setHover(null);}} aria-pressed={selected===space.id} aria-label={`选择或拖动${space.name}，${space.durationMinutes}分钟`} onClick={()=>setSelected(space.id)}><GripVertical size={16}/><span><strong>{space.name}</strong><small>{space.durationMinutes} 分钟 · {spaceTones[space.tone].name}</small></span></button>)}
 <form className="planner-place-form" onSubmit={e=>{e.preventDefault();if(selectedSpace)place(selectedSpace,day,timeMinutes(start));}}><h3>按时间放入</h3><label>场景<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="" disabled>选择专注空间</option>{state.focusSpaces.map(s=><option key={s.id} value={s.id}>{s.name} · {s.durationMinutes} 分钟</option>)}</select></label><label>星期<select value={day} onChange={e=>setDay(Number(e.target.value))}>{dayOrder.map(d=><option key={d} value={d}>{dayNames[d]}</option>)}</select></label><label>开始时间<input type="time" required value={start} onInput={e=>setStart(e.currentTarget.value)}/></label>{selectedSpace&&start&&<p>结束：{timeMinutes(start)+selectedSpace.durationMinutes>=1440?'次日 ':''}{formatMinute(timeMinutes(start)+selectedSpace.durationMinutes)}</p>}<button className="button primary" disabled={!selectedSpace||locked}><Plus size={14}/>放入时间表</button></form></aside>
 <div className="planner-calendar-wrap"><div className="planner-week-heading"><span>时间</span>{dayOrder.map(d=><span key={d} className={today.weekday===d?'is-today':''}>{dayNames[d]}</span>)}</div><div className="planner-scroll" ref={scroll}><div className="planner-calendar" style={{height}}><div className="planner-hours">{Array.from({length:24},(_,h)=><span key={h} style={{top:h*60*px}}>{String(h).padStart(2,'0')}:00</span>)}</div>{dayOrder.map(d=><div key={d} className={`planner-day ${hover?.day===d?'drag-over':''}`} aria-label={`${dayNames[d]}时间轴`} style={{height}} onDragOver={e=>{if(drag&&!locked){e.preventDefault();e.dataTransfer.dropEffect=drag.kind==='space'?'copy':'move';setHover(position(e,d));}}} onDrop={e=>drop(e,d)} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setHover(null);}}>
 {Array.from({length:24},(_,h)=><span key={h} className="planner-hour-line" style={{top:h*60*px}}/>)}
 {today.weekday===d&&<div className="planner-now" style={{top:today.minute*px}} aria-label={`现在 ${formatMinute(today.minute)}`}/>}
 {modules.flatMap(s=>segments(s).filter(part=>part.day===d).map(part=><button key={`${s.id}:${part.continued}`} type="button" className={`planner-block ${s.enabled?'':'is-paused'}`} style={{top:part.start*px,height:part.duration*px,'--space-color':spaceTones[s.focusSpace!.tone].color} as CSSProperties} draggable={!locked&&!part.continued} onDragStart={e=>beginDrag(e,{kind:'schedule',id:s.id})} onDragEnd={()=>{setDrag(null);setHover(null);}} onClick={()=>{setError('');setEditing(s);}} title={`${s.name} · ${range(s)} · ${s.focusSpace!.durationMinutes} 分钟${s.enabled?'':' · 已暂停'}`} aria-label={`调整${s.name}，${range(s)}`}><strong>{part.continued?'续 · ':''}{s.name}</strong>{part.duration>=45&&<span>{part.continued?'00:00':formatMinute(s.windows[0].start)} · {s.focusSpace!.durationMinutes} 分</span>}</button>))}
 {ghost&&segments(ghost).filter(part=>part.day===d).map(part=><div key={String(part.continued)} className={`planner-ghost ${conflict?'has-conflict':''}`} style={{top:part.start*px,height:part.duration*px}}><strong>{conflict?'与其他安排重叠':ghost.name}</strong><span>{range(ghost)}</span></div>)}
 </div>)}</div></div><div className="planner-calendar-note"><span>拖动时以 5 分钟对齐；精确时间可在左侧输入滚动查看全天</span><span>{modules.length} 个安排</span></div></div></div>
 {error&&<p className="error-text" role="alert">{error}</p>}{message&&<p className="planner-feedback" role="status">{message}</p>}
 <section className="planner-agenda"><div className="section-heading"><h3>已安排的专注</h3><span>模块保存独立配置，修改原空间不会改变已有安排</span></div>{!modules.length?<p className="muted">这一周还留着空白，把第一段专注放进来</p>:modules.map(s=><div className="planner-agenda-row" key={s.id}><span className="planner-color-dot" style={{background:spaceTones[s.focusSpace!.tone].color}}/><div><strong>{s.name}</strong><p>{range(s)} · {s.focusSpace!.durationMinutes} 分钟 · {s.enabled?'每周重复':'已暂停'}</p>{state.scheduleRuns.filter(r=>r.scheduleId===s.id).slice(-1).map(r=><p key={r.id} className="planner-run-status">最近一次：{new Intl.DateTimeFormat('zh-CN',{timeZone:state.settings.timezone,month:'numeric',day:'numeric'}).format(r.at)} · {{started:'已开始',busy:'已有专注，本次跳过',locked:'锁屏中，本次跳过',invalid:'场景配置失效，请重新安排'}[r.outcome]}</p>)}</div><button className="text-button" disabled={locked} onClick={()=>{setError('');setEditing(s);}}><Pencil size={14}/>调整</button><button className={`toggle ${s.enabled?'on':''}`} role="switch" aria-checked={s.enabled} aria-label={`启用安排${s.name}`} disabled={locked} onClick={()=>toggle(s)}><span/></button><button className="icon-button" aria-label={`删除安排${s.name}`} disabled={locked} onClick={()=>remove(s.id)}><Trash2 size={16}/></button></div>)}</section>
 {editing&&createPortal(<PlacementEditor key={editing.id} schedule={editing} locked={locked} error={error} close={()=>setEditing(null)} save={(day,start)=>place(editing.focusSpace!,day,start,editing.id)} remove={()=>remove(editing.id)}/>,document.getElementById('root')!)}
 </section>;
}
function PlacementEditor({schedule,locked,error,close,save,remove}:{schedule:Schedule;locked:boolean;error:string;close:()=>void;save:(day:number,start:number)=>void;remove:()=>void}){
 const [day,setDay]=useState(schedule.windows[0].days[0]),[start,setStart]=useState(formatMinute(schedule.windows[0].start));
 return <div className="modal-backdrop"><section className="modal narrow" role="dialog" aria-modal="true" aria-labelledby="placement-title"><div className="modal-heading"><h2 id="placement-title">调整「{schedule.name}」</h2><button className="icon-button" aria-label="关闭安排编辑" onClick={close}><X/></button></div><p>{schedule.focusSpace!.durationMinutes} 分钟 · 结束时间随开始时间自动移动</p><form onSubmit={e=>{e.preventDefault();save(day,timeMinutes(start));}}><div className="form-grid"><label>星期<select value={day} onChange={e=>setDay(Number(e.target.value))}>{dayOrder.map(d=><option key={d} value={d}>{dayNames[d]}</option>)}</select></label><label>开始时间<input required type="time" value={start} onInput={e=>setStart(e.currentTarget.value)}/></label></div>{error&&<p className="error-text" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="text-button danger" disabled={locked} onClick={remove}>删除这次安排</button><button type="button" className="button secondary" onClick={close}>取消</button><button className="button primary" disabled={locked}>保存安排</button></div></form></section></div>;
}
