import {FocusBackgroundPicker,FocusPhoto} from './FocusBackground';
import {createPortal} from 'react-dom';
import {useState,type CSSProperties} from 'react';
import {ArrowRight,Plus,Play,Pencil,Trash2,X} from 'lucide-react';
import {FocusSpaceSchema,modeLabels,type AppState,type FocusSpace} from '../../../packages/core/src/model';
import {spaceTones} from '../../../packages/core/src/focus-spaces';
export type SpaceChange=(fn:(state:AppState)=>AppState)=>void;
export function SpaceLandscape({tone}:{tone:FocusSpace['tone']}){
 return <svg className="space-landscape" viewBox="0 0 320 84" preserveAspectRatio="none" aria-hidden="true"><circle cx="250" cy="26" r="16" fill="currentColor" opacity=".18"/>{tone==='blue'?<><path d="M0 55 Q40 35 80 55 T160 55 T240 55 T320 55 V84 H0Z" fill="currentColor" opacity=".16"/><path d="M0 72 Q40 54 80 72 T160 72 T240 72 T320 72 V84 H0Z" fill="currentColor" opacity=".22"/></>:<><path d="M0 80 63 24 121 66 186 37 260 84Z" fill="currentColor" opacity=".14"/><path d="M75 84 151 45 217 71 291 47 320 72 V84Z" fill="currentColor" opacity=".24"/></>}</svg>;
}
export function FocusSpaces({state,change,onStart,onTimetable}:{state:AppState;change:SpaceChange;onStart:(space:FocusSpace)=>void;onTimetable:()=>void}){
 const [editing,setEditing]=useState<FocusSpace|null>(null);
 const active=state.sessions.some(s=>s.status==='active');
 const create=()=>setEditing({id:crypto.randomUUID(),name:'',durationMinutes:25,projectId:state.projects[0]?.id??'personal',listIds:state.lists[0]?[state.lists[0].id]:[],mode:'friction',tone:'mint'});
 return <section className="space-library"><div className="section-heading"><div><h2>我的专注空间 <span>{state.focusSpaces.length}</span></h2><p>把常用的场景留下，下次一键进入</p></div><button className="button secondary" onClick={create}><Plus size={16}/>新建空间</button></div>
 {state.focusSpaces.length?<div className="space-grid">{state.focusSpaces.map(space=><article key={space.id} className={`space-card tone-${space.tone}`} style={{'--space-color':spaceTones[space.tone].color} as CSSProperties}><SpaceLandscape tone={space.tone}/><FocusPhoto state={state} backgroundId={space.backgroundId}/><div className="space-card-top"><span>{spaceTones[space.tone].name} · {modeLabels[space.mode]}</span><button className="icon-button" aria-label={`编辑空间${space.name}`} onClick={()=>setEditing(space)}><Pencil size={15}/></button></div><h3>{space.name}</h3><p>{state.projects.find(p=>p.id===space.projectId)?.name??'项目已删除'} · {space.listIds.length} 个屏蔽列表</p><div className="space-card-bottom"><strong>{space.timerMode==='countup'?'00:00':space.durationMinutes}<small>{space.timerMode==='countup'?'正向计时':'分钟'}</small></strong><button className="button space-start" disabled={active} aria-label={`开始${space.name}`} onClick={()=>onStart(space)}><Play size={14}/>{active?'专注进行中':'进入专注'}</button></div></article>)}</div>:<div className="space-empty"><div><h3>给不同的事情，留不同的空间</h3><p>例如：25 分钟晨读、50 分钟深度工作、15 分钟晚间复盘</p></div><button className="button primary" onClick={create}>创建第一个空间 <ArrowRight size={16}/></button></div>}
 <div className="space-library-foot"><span>场景可保存名称、时长、配色、项目和屏蔽列表</span><button className="text-button" onClick={onTimetable}>安排到时间表 <ArrowRight size={14}/></button></div>
 {editing&&createPortal(<SpaceEditor onImport={asset=>change(s=>({...s,focusBackgrounds:[...s.focusBackgrounds,asset]}))} state={state} space={editing} close={()=>setEditing(null)} save={space=>{change(s=>({...s,focusSpaces:[...s.focusSpaces.filter(x=>x.id!==space.id),space]}));setEditing(null);}} remove={()=>{change(s=>({...s,focusSpaces:s.focusSpaces.filter(x=>x.id!==editing.id)}));setEditing(null);}}/>,document.getElementById('root')!)}
 </section>;
}
function SpaceEditor({state,space,close,save,remove,onImport}:{state:AppState;space:FocusSpace;close:()=>void;save:(space:FocusSpace)=>void;remove:()=>void;onImport:(asset:AppState['focusBackgrounds'][number])=>void}){
 const [draft,setDraft]=useState(space),[error,setError]=useState('');const patch=(value:Partial<FocusSpace>)=>setDraft(s=>({...s,...value}));
 return <div className="modal-backdrop"><section className="modal narrow" role="dialog" aria-modal="true" aria-labelledby="space-editor-title"><div className="modal-heading"><div><span className="eyebrow">为一件事，设计一段时间</span><h2 id="space-editor-title">{state.focusSpaces.some(s=>s.id===space.id)?'编辑专注空间':'新建专注空间'}</h2></div><button className="icon-button" aria-label="关闭空间编辑" onClick={close}><X/></button></div><form onSubmit={e=>{e.preventDefault();const result=FocusSpaceSchema.safeParse(draft);if(!result.success){setError('请填写名称，并设置 1–720 分钟的整数时长');return;}save(result.data);}}><div className="form-grid"><label className="span2">场景名称<input autoFocus required maxLength={30} value={draft.name} onChange={e=>patch({name:e.target.value})} placeholder="例如：深度阅读"/></label><label>计时方式<select value={draft.timerMode??'countdown'} onChange={e=>patch({timerMode:e.target.value as 'countup'|'countdown',...(e.target.value==='countup'&&draft.mode==='strict'?{mode:'friction' as const}:{})})}><option value="countdown">倒计时 · 到时完成</option><option value="countup">正向计时 · 手动完成</option></select></label><label>{draft.timerMode==='countup'?'时间表预留时长（分钟）':'专注时长（分钟）'}<input required type="number" min={1} max={720} step={1} value={Number.isNaN(draft.durationMinutes)?'':draft.durationMinutes} onChange={e=>patch({durationMinutes:e.target.valueAsNumber})}/></label><label>归属项目<select value={draft.projectId} onChange={e=>patch({projectId:e.target.value})}>{state.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{draft.timerMode==='countup'&&<p className="small muted">直接启动后从 00:00 累计，由你完成；放入时间表时按预留时长结束正向计时不使用严格模式</p>}<FocusBackgroundPicker state={state} tone={draft.tone} backgroundId={draft.backgroundId} onChange={(tone,backgroundId)=>patch({tone,backgroundId})} onImport={onImport}/><div className="form-section"><h3>专注时屏蔽</h3><div className="list-checks">{state.lists.map(list=><label key={list.id}><input type="checkbox" checked={draft.listIds.includes(list.id)} onChange={e=>patch({listIds:e.target.checked?[...draft.listIds,list.id]:draft.listIds.filter(id=>id!==list.id)})}/>{list.name}</label>)}</div></div><label>自律等级<select value={draft.mode} onChange={e=>patch({mode:e.target.value as FocusSpace['mode']})}><option value="gentle">温和提醒</option><option value="friction">增加摩擦</option><option value="strict" disabled={draft.timerMode==='countup'}>严格自律（开始后不可提前结束）</option></select></label><p className="small muted">修改或删除空间不会改变已放入时间表的模块；已有安排可在时间表中单独调整</p>{error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-actions">{state.focusSpaces.some(s=>s.id===space.id)&&<button type="button" className="text-button danger" onClick={remove}><Trash2 size={14}/>删除空间</button>}<button type="button" className="button secondary" onClick={close}>取消</button><button className="button primary" type="submit">保存空间</button></div></form></section></div>;
}
